# LP 3

**1. Importa librariile necesare**

**2. Citeste datele din fisierul "FuelConsumption.csv" intr-un dataframe folosind pd.read_csv()

dupa ce ai mapat Google Drive**

from google.colab import drive
drive.mount('/content/drive')

*FuelConsumption.csv:* Este un set de date ce contine informatii privind consumul de combustibil al diverselor tipuri de autoturisme si emisiile CO2 din Canada.

# Intelegerea datelor

In [1]:
# Afisarea primelor 10 linii din tabel

df.head()

# Informatii cu privire la dataframe - nr linii, coloane si tipul datelor

df.info()

**Explorarea datelor**

Să facem mai întâi o analiza descriptivă a datelor noastre.

In [2]:
# Statistici descriptive

df.describe()

***INTERPRETARE***

In [3]:
# Selectarea catorva variabile pentru a le explora mai in detaliu
cdf = df[[var1,var2,var3,var4]]
cdf.head()

In [4]:
# Reprezentarea grafica - distributia variabilelor

**Reprezentati fiecare dintre aceste caracteristici în raport cu Emisiile de CO2, pentru a vedea daca relatia lor este liniara si realizati si un heatmap pentru calculul corelatiilor:**

In [5]:
#Distributile variabilelor si scatterplot

sns.pairplot(df);

NameError: name 'sns' is not defined

In [6]:
# Reprezentare grafica Heatmap pentru coeficientii de corelatie liniara

corrmat = df.corr(numeric_only=True)
sns.heatmap(corrmat, annot=True)
plt.show()

NameError: name 'df' is not defined

In [7]:
# Investigarea valorilor lipsa, tipului de date, si forma datelor.
df.info()

NameError: name 'df' is not defined

# Preprocesarea datelor:
Caracteristicile numerice pot fi logaritmate pentru a le transforma in variabile mai apropiate de cele repartizate normal.
Caracteristicile categoriale vor fi transformate in variabile binare
Valorile numerice lipsă (NaN) vor fi inlocuite cu media coloanelor respective

In [9]:
# Care variabile sunt numerice si care sunt categoriale?

# Selectarea caracteristicilor categoriale
cate_data = df.select_dtypes("object").columns
print("Categorical variables = ",cate_data.shape)

# Selectarea caracteristicilor numerice
num_data = df.select_dtypes(include=["int64", "float64"]).columns
print("Numerical variables = ",num_data.shape)

NameError: name 'df' is not defined

In [10]:
# Este utila logaritmarea variabilei target 'CO2 Emissions'?
Dupa logaritmare comparam distributiile si valorile Skewness si Kurtosis.

emissions = pd.DataFrame({"emissions":df['CO2 Emissions'], "log(emissions + 1)":np.log1p(df['CO2 Emissions'])})
emissions.hist()

print(f"Skewness: {emissions.skew()}")
print(f"Kurtosis: {emissions.kurt()}")

SyntaxError: invalid syntax (ipython-input-39791063.py, line 2)

In [11]:
#Logaritmarea variabilei target in dataframe: CO2 Emmissions
df['CO2 Emissions'] = np.log1p(df['CO2 Emissions'])
df

NameError: name 'np' is not defined

## **EXERCITIU:**

**Despre setul de date**

Sunt colectate date despre diferite zone din Boston pentru a crea un model care sa pota prezice prețul mediu al caselor pentru acea zonă.
Setul de date avea informații despre zone/orașe, nu despre case individuale:
- CRIM: Crimă pe cap de locuitor
- ZN: Proporția de teren rezidențial zonat pentru loturi de peste 25.000 sq.ft.
- INDUS: Proporția de hectare comerciale non-retail pe oraș
- CHAS: variabilă dummy Charles River (= 1 dacă delimitează râul; 0 în caz contrar)
- NOX: concentrație de oxizi nitrici (părți la 10 milioane)
- RM: Numărul mediu de camere pe locuință
- Vârsta: Proporția unităților ocupate de proprietar construite înainte de 1940
- DIS: Distanțe ponderate până la cinci centre de angajare din Boston
- RAD: Indice de accesibilitate la autostrăzile radiale
- TAXĂ: Cota de impozit pe proprietate la valoarea completă pentru 10.000 USD
- PTRAIO: Raport elev-profesor pe oraș
- LSTAT: Statutul procentual mai scăzut al populației
- MEDV: Valoarea medie a caselor ocupate de proprietari în 1000 de dolari

   https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/real_estate_data.csv



***Analizati si preprocesati baza de date***

In [ ]:
url = "https://cf-courses-data.s3.us.cloud-object-storage.appdomain.cloud/IBMDeveloperSkillsNetwork-ML0101EN-SkillsNetwork/labs/Module%203/data/real_estate_data.csv"

df = pd.read_csv(url)

print(df.head())   # afișează primele 5 rânduri

      CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  PTRATIO  \
0  0.00632  18.0   2.31   0.0  0.538  6.575  65.2  4.0900    1  296     15.3
1  0.02731   0.0   7.07   0.0  0.469  6.421  78.9  4.9671    2  242     17.8
2  0.02729   0.0   7.07   0.0  0.469  7.185  61.1  4.9671    2  242     17.8
3  0.03237   0.0   2.18   0.0  0.458  6.998  45.8  6.0622    3  222     18.7
4  0.06905   0.0   2.18   0.0  0.458  7.147  54.2  6.0622    3  222     18.7

   LSTAT  MEDV
0   4.98  24.0
1   9.14  21.6
2   4.03  34.7
3   2.94  33.4
4    NaN  36.2

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  LSTAT    486 non-null    float64
 12  MEDV     506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB

# Curățarea bazei de date

In [ ]:
def drop_columns_with_high_nulls(df, threshold_percentage):

    # Calculam numarul maxim de valori lipsa admise pe baza unei limite definite
    threshold = len(df) * (threshold_percentage / 100)

    # Obtinem lista variabilelor ce trebuie inlaturate din analiza
    dropped_columns = df.columns[df.isnull().sum() > threshold]

    # stergem variabilele cu multe valori lipsa
    df_cleaned = df.drop(dropped_columns,  axis=1)

    return df_cleaned, dropped_columns


threshold_percentage = 10  # Poate fi schimbată această limită - noi am considerat ca un număr de peste 30 valori lipsă este prea ridicat (adică un procent de peste 3,5%)

# Curățarea tabelului prin eliminarea coloanelor cu multe valori lipsă și obținerea listei variabilelor eliminate
df_cleaned, dropped_columns = drop_columns_with_high_nulls(df, threshold_percentage)

# Afisarea tabelului curățat
print("Cleaned DataFrame:")
print(df_cleaned)

# Display the list of columns that were dropped
print("\nDropped Columns:")
print(dropped_columns)

df = df_cleaned
#df.info()

Cleaned DataFrame:
        CRIM    ZN  INDUS  CHAS    NOX     RM        AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31   0.0  0.538  6.575  65.200000  4.0900    1  296
1    0.02731   0.0   7.07   0.0  0.469  6.421  78.900000  4.9671    2  242
2    0.02729   0.0   7.07   0.0  0.469  7.185  61.100000  4.9671    2  242
3    0.03237   0.0   2.18   0.0  0.458  6.998  45.800000  6.0622    3  222
4    0.06905   0.0   2.18   0.0  0.458  7.147  54.200000  6.0622    3  222
..       ...   ...    ...   ...    ...    ...        ...     ...  ...  ...
501  0.06263   0.0  11.93   0.0  0.573  6.593  69.100000  2.4786    1  273
502  0.04527   0.0  11.93   0.0  0.573  6.120  76.700000  2.2875    1  273
503  0.06076   0.0  11.93   0.0  0.573  6.976  91.000000  2.1675    1  273
504  0.10959   0.0  11.93   0.0  0.573  6.794  89.300000  2.3889    1  273
505  0.04741   0.0  11.93   0.0  0.573  6.030  68.518519  2.5050    1  273

     PTRATIO      LSTAT  MEDV
0       15.3   4.980000  24.0
1       17.8   9.140000  21.6
2       17.8   4.030000  34.7
3       18.7   2.940000  33.4
4       18.7  12.715432  36.2
..       ...        ...   ...
501     21.0  12.715432  22.4
502     21.0   9.080000  20.6
503     21.0   5.640000  23.9
504     21.0   6.480000  22.0
505     21.0   7.880000  11.9

[506 rows x 13 columns]

Dropped Columns:
Index([], dtype='object')

Nu a fost inlaturata nici o variabila

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  LSTAT    486 non-null    float64
 12  MEDV     506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB

In [ ]:
# Care variabile sunt numerice si care sunt categoriale?

# Selectarea caracteristicilor categoriale
cate_data = df.select_dtypes("object").columns
print("Categorical variables = ",cate_data.shape)

# Selectarea caracteristicilor numerice
num_data = df.select_dtypes(include=["int64", "float64"]).columns
print("Numerical variables = ",num_data.shape)

Categorical variables =  (0,)
Numerical variables =  (13,)

In [ ]:
#Inlocuirea valorilor lipsa cu media
for col in num_data:
    df[col].fillna(df[col].mean(), inplace=True)

/tmp/ipython-input-94961541.py:3: FutureWarning:

A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 13 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     506 non-null    float64
 1   ZN       506 non-null    float64
 2   INDUS    506 non-null    float64
 3   CHAS     506 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      506 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  LSTAT    506 non-null    float64
 12  MEDV     506 non-null    float64
dtypes: float64(11), int64(2)
memory usage: 51.5 KB

**1. Analizati aceasta baza de date dupa inlocuirea valorilor lipsa**

**2. Incercati si alte tipuri de imputari simple sau avansate**